# Dependencies
markdown:         kramdown 
highlighter:      Rouge

# Permalinks
permalink:        pretty
plugins: [jekyll-paginate]

# Setup
title:            Zhenbo Sun
tagline:          'A Jekyll theme'
description:      'Department Computer Science and Technology, Tsinghua University'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          4.0.0

github:           https://github.com/Bran-Sun
